---
- hosts: 10.0.0.5
  become: yes
  tasks:
  - include_tasks: myfile.yml 
  - name: i want to  install webserver
    apt:
      name: apache2
      state: present
  - name: copy static file from master to nodes
    copy:
      src: mystaticfile
      dest: /home/maha/
