---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks: 
  - name: in task, i want to install  apache2  webserver on ubuntu ansible node
    apt:
      name: "{{mywebpackonubuntu}}"
      state: present
    when: ansible_os_family=="Debian"
  - name: in task, i want to starts apache2 webserver on ubuntu anible nodes
    service:
      name: "{{mywebpackonubuntu}}"
      state: started
    when: ansible_os_family=="Debian"

  - name: install httpd webserver on  redhat ansible node
    dnf:
       name: "{{mywebpackonredhat}}"
       state: present
    when: ansible_os_family=="RedHat"


  - name: start webserver on redhat ansible node
    service:
       name: "{{mywebpackonredhat}}"
       state: started
    when: ansible_os_family =="RedHat"
   